AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for Saidatechwebapp Bucket
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: saidatechwebapp
      AccessControl: PublicRead
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket